#!/bin/bash

./sshall.py --build 'bash -c "cd /srcML; git pull"'

./sshall.py --build 'bash -c "cd /srcML/dist; make clean; make"'
./sshall.py --build 'bash -c "chown -R srcml:srcml /srcML"'

#scp fedora15build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora15
#scp fedora16build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora16
scp fedora17build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora17
scp fedora18build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora18
scp fedora19build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora19

#scp fedora15build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora15-64
#scp fedora16build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora16-64
scp fedora17build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora17-64
scp fedora18build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora18-64
scp fedora19build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Fedora19-64

scp ubuntu10build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu10.04
#scp ubuntu11build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu11.04
scp ubuntu12build:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu12.04

scp ubuntu10build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu10.04-64
#scp ubuntu11build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu11.04-64
scp ubuntu12build64:/srcML/trunk/dist/srcML*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu12.04-64

./sshall.py --fedora --build --19 'bash -c "cd /srcML/dist; make clean; make windowsdyn"'
./sshall.py --fedora --build --19 'bash -c "chown -R srcml:srcml /srcML"'
scp fedora19build:/srcML/trunk/dist/srcML*.zip ~/Dropbox/srcML/Windows

cd ~/Dropbox/srcML/Windows; unzip srcML-Win.zip
cd

cd srcML; git pull
cd

cd srcML/dist; make clean; make;

man srcML/src2srcml.1.gz | man2html > srcML/src2srcml.html
man srcML/srcml2src.1.gz | man2html > srcML/srcml2src.html

tar czf srcML.tar.gz srcML
cp *.tar.gz ~/Dropbox/srcML/Unix/OSX
cd
