volumes:
  ccache: # Optional ccache
  data: # Input data
  dist: # Installers

x-configuration: &CONFIGURATION
  volumes:
    - .:/srcML:ro
    - ccache:/ccache
    - data:/Data:ro
    - dist:/Builds
  working_dir: /srcML
  command: bash -c "${COMPOSE_COMMAND-cmake --workflow --preset ci-$$WORKFLOW}"
  pull_policy: always

x-utilities: &UTILITIES
  image: srcml/utility
  profiles: [utility]
  volumes:
    - dist:/dist

services:

  ubuntu_26_04:
    image: srcml/ubuntu:26.04
    platform: ${PLATFORM}
    profiles: [ubuntu, package, latest]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  ubuntu_25_10:
    image: srcml/ubuntu:25.10
    platform: ${PLATFORM}
    profiles: [ubuntu, package]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  ubuntu_25_04:
    image: srcml/ubuntu:25.04
    platform: ${PLATFORM}
    profiles: [ubuntu, package]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  ubuntu_24_10:
    image: srcml/ubuntu:24.10
    platform: ${PLATFORM}
    profiles: [ubuntu, package]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  ubuntu_24_04:
    image: srcml/ubuntu:24.04
    platform: ${PLATFORM}
    profiles: [ubuntu, package, latest]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  ubuntu_22_04:
    image: srcml/ubuntu:22.04
    platform: ${PLATFORM}
    profiles: [ubuntu, package]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  ubuntu_20_04:
    image: srcml/ubuntu:20.04
    platform: ${PLATFORM}
    profiles: [ubuntu, package, oldest]
    environment:
      - WORKFLOW=ubuntu
    <<: *CONFIGURATION

  fedora_44:
    image: srcml/fedora:44
    platform: ${PLATFORM}
    profiles: [fedora, package, latest]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  fedora_43:
    image: srcml/fedora:43
    platform: ${PLATFORM}
    profiles: [fedora, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  fedora_42:
    image: srcml/fedora:42
    platform: ${PLATFORM}
    profiles: [fedora, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  fedora_41:
    image: srcml/fedora:41
    platform: ${PLATFORM}
    profiles: [fedora, package, latest]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  fedora_40:
    image: srcml/fedora:40
    platform: ${PLATFORM}
    profiles: [fedora, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  fedora_39:
    image: srcml/fedora:39
    platform: ${PLATFORM}
    profiles: [fedora, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  fedora_38:
    image: srcml/fedora:38
    platform: ${PLATFORM}
    profiles: [fedora, package, oldest]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15_6:
    image: srcml/opensuse:15.6
    platform: ${PLATFORM}
    profiles: [opensuse, package, latest]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15_5:
    image: srcml/opensuse:15.5
    platform: ${PLATFORM}
    profiles: [opensuse, package, latest]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15_4:
    image: srcml/opensuse:15.4
    platform: ${PLATFORM}
    profiles: [opensuse, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15_3:
    image: srcml/opensuse:15.3
    platform: ${PLATFORM}
    profiles: [opensuse, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15_2:
    image: srcml/opensuse:15.2
    platform: ${PLATFORM}
    profiles: [opensuse, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15_1:
    image: srcml/opensuse:15.1
    platform: ${PLATFORM}
    profiles: [opensuse, package, oldest]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_15:
    image: srcml/opensuse:15
    platform: ${PLATFORM}
    profiles: [opensuse, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION

  opensuse_tumbleweed:
    image: srcml/opensuse:tumbleweed
    platform: ${PLATFORM}
    profiles: [opensuse, package]
    environment:
      - WORKFLOW=rpm
    <<: *CONFIGURATION
