#!/bin/bash

# list of all global variables and what they should be replaced with
REPLACEMENTS="LANGUAGE_FLAG_SHORT,l
LANGUAGE_FLAG_LONG,language
DIRECTORY_FLAG_SHORT,idk
DIRECTORY_FLAG_LONG,idk
FILENAME_FLAG_SHORT,idk
FILENAME_FLAG_LONG,filename
SRCVERSION_FLAG_SHORT,idk
SRCVERSION_FLAG_LONG,idk
SRC_ENCODING_FLAG_SHORT,t
SRC_ENCODING_FLAG_LONG,src-encoding
EXPRESSION_MODE_FLAG_SHORT,e
EXPRESSION_MODE_FLAG_LONG,idk
ENCODING_FLAG_SHORT,idk
ENCODING_FLAG_LONG,idk
OUTPUT_FLAG_SHORT,o
OUTPUT_FLAG_LONG,output
ARCHIVE_FLAG_SHORT,r
ARCHIVE_FLAG_LONG,archive
SRC_ENCODING_FLAG_SHORT,idk
SRC_ENCODING_FLAG_LONG,encoding
NO_XML_DECL_SHORT,idk
NO_XML_DECL_LONG,no-xml-declaration
NO_NAMESPACE_DECL_SHORT,idk
NO_NAMESPACE_DECL_LONG,no-namespace-decl
INTERACTIVE_FLAG_SHORT,i
INTERACTIVE_FLAG_LONG,interactive
FILES_FROM_LONG,files-from
DEBUG_FLAG_SHORT,D
DEBUG_FLAG_SHORT,debug
SRCML_EXT_LITERAL_NS_PREFIX_DEFAULT,idk
SRCML_EXT_LITERAL_NS_URI,idk
SRCML_ERR_NS_PREFIX_DEFAULT,idk
SRCML_CPP_NS_PREFIX_DEFAULT,idk
SRCML_EXT_POSITION_NS_PREFIX_DEFAULT,idk
SRCML_ERR_NS_URI,http:\/\/www.sdml.info\/srcML\/srcerr
SRCML_SRC_NS_URI,idk
SRCML_CPP_NS_URI,idk
SRCML_EXT_POSITION_NS_URI,idk
XMLNS_FLAG,xmlns
VERBOSE_FLAG_SHORT,v
VERBOSE_FLAG_SHORT,verbose
REGISTER_EXTENSION_FLAG_LONG,register-ext
LITERAL_FLAG,idk
MAX_THREADS_FLAG_LONG,max-threads
IN_ORDER_FLAG_LONG,in-order
EXTERNAL_LONG,external
TABS_FLAG,tabs
COMPRESS_FLAG_SHORT,z
COMPRESS_FLAG_LONG,compress
STATUS_SUCCESS,0
STATUS_ERROR,idk
STATUS_INPUTFILE_PROBLEM,idk
STATUS_UNKNOWN_OPTION,idk
STATUS_UNKNOWN_ENCODING,idk
STATUS_INVALID_LANGUAGE,idk
STATUS_INVALID_OPTION_COMBINATION,idk
STATUS_TERMINATED,idk
QUIET_FLAG_SHORT,q
QUIET_FLAG_LONG,quiet
VERSION_FLAG_LONG,version
VERSION_FLAG_SHORT,V
HELP_FLAG_SHORT,h
HELP_FLAG_LONG,help"

INPUT=$1
OUTPUT=$2
rm "$OUTPUT"
cp "$INPUT" "$OUTPUT"

# replace each expression from the list
while IFS=',' read -r target replacement; do
	sed -i -e "s/$target/$replacement/g" $OUTPUT
done < <(echo "$REPLACEMENTS")
