#!/bin/bash

# list of all global variables and what they should be replaced with
REPLACEMENTS="SHOW_LANGUAGE_FLAG_LONG,show-language
SHOW_DIRECTORY_FLAG_LONG,show-directory
SHOW_FILENAME_FLAG_LONG,show-filename
SHOW_SRC_VERSION_FLAG_LONG,show-src-version
SHOW_TIMESTAMP_FLAG_LONG,show-timestamp
SHOW_HASH_FLAG_LONG,show-hash
SHOW_XML_ENCODING_FLAG_LONG,show-encoding
SHOW_UNIT_COUNT_FLAG_LONG,show-unit-count
LANGUAGE_FLAG_SHORT,l
LANGUAGE_FLAG_LONG,language
DIRECTORY_FLAG_SHORT,d
DIRECTORY_FLAG_LONG,directory
FILENAME_FLAG_SHORT,f
FILENAME_FLAG_LONG,filename
SRCVERSION_FLAG_SHORT,s
SRCVERSION_FLAG_LONG,src-version
SRC_ENCODING_FLAG_SHORT,t
SRC_ENCODING_FLAG_LONG,src-encoding
HASH_FLAG_LONG,hash
EXPRESSION_MODE_FLAG_SHORT,e
EXPRESSION_MODE_FLAG_LONG,expression
XML_ENCODING_FLAG_SHORT,x
XML_ENCODING_FLAG_LONG,xml-encoding
LONG_INFO_FLAG_SHORT,L
LONG_INFO_FLAG_LONG,longinfo
INFO_FLAG_SHORT,i
INFO_FLAG_LONG,info
PREFIX_FLAG_SHORT,p
PREFIX_FLAG_LONG,prefix
LIST_FLAG_LONG,list
OUTPUT_FLAG_SHORT,o
OUTPUT_FLAG_LONG,output
OUTPUT_XML_FLAG_SHORT,X
OUTPUT_XML_FLAG_LONG,output-xml
OUTPUT_SRC_FLAG_SHORT,S
OUTPUT_SRC_FLAG_LONG,output-src
ARCHIVE_FLAG_SHORT,r
ARCHIVE_FLAG_LONG,archive
NO_XML_DECL_LONG,no-xml-declaration
NO_NAMESPACE_DECL_LONG,no-namespace-decl
INTERACTIVE_FLAG_SHORT,c
INTERACTIVE_FLAG_LONG,interactive
FILES_FROM_LONG,files-from
DEBUG_FLAG_SHORT,g
DEBUG_FLAG_LONG,debug
SRCML_EXT_LITERAL_NS_PREFIX_DEFAULT,idk
SRCML_EXT_LITERAL_NS_URI,idk
SRCML_ERR_NS_PREFIX_DEFAULT,idk
SRCML_CPP_NS_PREFIX_DEFAULT,idk
SRCML_EXT_POSITION_NS_PREFIX_DEFAULT,idk
SRCML_ERR_NS_URI,http:\/\/www.sdml.info\/srcML\/srcerr
SRCML_SRC_NS_URI,idk
SRCML_CPP_NS_URI,idk
SRCML_EXT_POSITION_NS_URI,http:\/\/www.sdml.info\/srcML\/position
XMLNS_FLAG,xmlns
VERBOSE_FLAG_SHORT,v
VERBOSE_FLAG_LONG,verbose
REGISTER_EXTENSION_FLAG_LONG,register-ext
LITERAL_FLAG,idk
MAX_THREADS_FLAG_LONG,max-threads
IN_ORDER_FLAG_LONG,in-order
EXTERNAL_LONG,external
TABS_FLAG,tabs
COMPRESS_FLAG_SHORT,z
COMPRESS_FLAG_LONG,compress
STATUS_SUCCESS,0
STATUS_ERROR,idk
STATUS_INPUTFILE_PROBLEM,idk
STATUS_UNKNOWN_OPTION,idk
STATUS_UNKNOWN_ENCODING,idk
STATUS_INVALID_LANGUAGE,idk
STATUS_INVALID_OPTION_COMBINATION,idk
STATUS_TERMINATED,idk
QUIET_FLAG_SHORT,q
QUIET_FLAG_LONG,quiet
VERSION_FLAG_LONG,version
VERSION_FLAG_SHORT,V
HELP_FLAG_SHORT,h
HELP_FLAG_LONG,help"

INPUT=$1
OUTPUT=$2
rm "$OUTPUT"
cp "$INPUT" "$OUTPUT"

# replace each expression from the list
while IFS=',' read -r target replacement; do
	sed -i -e "s/$target/$replacement/g" $OUTPUT
done < <(echo "$REPLACEMENTS")
