#!/bin/bash

./prlctlall.py --fedora --build resume; sleep 15
./build_srcML --release fedora
./prlctlall.py --fedora --build suspend

./prlctlall.py --ubuntu --build resume; sleep 15
./build_srcML --release ubuntu
./prlctlall.py --ubuntu --build suspend

./prlctlall.py --mint --build resume; sleep 15
./build_srcML --release mint
./prlctlall.py --mint --build suspend

./prlctlall.py --suse --build resume; sleep 15
./build_srcML --release suse
./prlctlall.py --suse --build suspend

./prlctlall.py --mac --build resume; sleep 15
./build_srcML --release mac
./prlctlall.py --mac --build suspend