#!/bin/bash

./vmctl.py --fedora --build resume; sleep 15
./build_srcML --release fedora
./vmctl.py --fedora --build suspend

./vmctl.py --ubuntu --build resume; sleep 15
./build_srcML --release ubuntu
./vmctl.py --ubuntu --build suspend

./vmctl.py --mint --build resume; sleep 15
./build_srcML --release mint
./vmctl.py --mint --build suspend

./vmctl.py --suse --build resume; sleep 15
./build_srcML --release suse
./vmctl.py --suse --build suspend

./vmctl.py --mac --build resume; sleep 15
./build_srcML --release mac
./vmctl.py --mac --build suspend