#!/bin/bash

pushd /Users/srcml/Documents/srcML/virtual_machines/

# fedora
./vmctl.py --build --fedora --20 resume; sleep 15
./nightly_cdash "--fedora20build --~64" "Fedora-20"
./nightly_cdash "--fedora20build64" "Fedora-20-64bit"
./vmctl.py --build --fedora --20 suspend
./vmctl.py --build --fedora --21 resume; sleep 15
./nightly_cdash "--fedora21build --~64" "Fedora-21"
./nightly_cdash "--fedora20build64" "Fedora-21-64bit"
./vmctl.py --build --fedora --21 suspend

# open suse
./vmctl.py --build --suse resume; sleep 15
./nightly_cdash "--suse13build --~64" "OpenSUSE-13.1"
./nightly_cdash "--suse13build64" "OpenSUSE-13.1-64bit"
./nightly_cdash "--suse132build --~64" "OpenSUSE-13.2"
./nightly_cdash "--suse132build64" "OpenSUSE-13.2-64bit"
./vmctl.py --build --suse suspend

# ubuntu
./vmctl.py --build --ubuntu --12 resume; sleep 15
./nightly_cdash "--ubuntu12build --~64" "Ubuntu-12.04"
./nightly_cdash "--ubuntu12build64" "Ubuntu-12.04-64bit"
./vmctl.py --build --ubuntu --12 suspend

./vmctl.py --build --ubuntu --14 resume; sleep 15
./nightly_cdash "--ubuntu14build --~64" "Ubuntu-14.04"
./nightly_cdash "--ubuntu14build64" "Ubuntu-14.04-64bit"
./vmctl.py --build --ubuntu --14 suspend

./vmctl.py --build --ubuntu --16 resume; sleep 15
./nightly_cdash "--ubuntu16build64" "Ubuntu-16.04-64bit"
./vmctl.py --build --ubuntu --16 suspend

# mint
./vmctl.py --build --mint --13 resume; sleep 15
./nightly_cdash "--mint13build --~64" "Mint-13"
./nightly_cdash "--mint13build64" "Mint-13-64bit"
./vmctl.py --build --mint --13 suspend

./vmctl.py --build --mint --17 resume; sleep 15
./nightly_cdash "--mint17build --~64" "Mint-17"
./nightly_cdash "--mint17build64" "Mint-17(64-bit)"
./nightly_cdash "--mint171build --~64" "Mint-17.1"
./nightly_cdash "--mint171build64" "Mint-17.1-64bit"
./vmctl.py --build --mint --17 suspend

# mac
./vmctl.py --mac --build resume; sleep 15
./nightly_cdash "--mac" "Mac-OSX-Mavericks"
./vmctl.py --mac --build suspend

popd
