#!/bin/bash

ARG=$1
NAME=$2

./sshall.py $ARG "bash -c \"date \\\"$(date "+%m%d%H%M%Y.%S")\\\"\""

./sshall.py $ARG 'bash -c "cd /srcML; git clean -fdx; git checkout develop; git pull"'

./sshall.py $ARG "bash -c \"rm -rf /ci-build; mkdir /ci-build;\""

./sshall.py $ARG "bash -c \"cd /ci-build; cmake -DBUILD_CLI_TESTS=ON -DBUILD_UNIT_TESTS=ON -DBUILD_TIMING_TESTS=ON /srcML\""

./sshall.py $ARG "bash -c \"cd /ci-build; make -j2; ctest -VV -D Nightly --overwrite Site='$NAME'\""
