#!/bin/bash

ARG=$1
NAME=$2

./sshall.py $ARG "bash -c \"date \\\"$(date "+%m%d%H%M%Y.%S")\\\"\""

# start fresh
./sshall.py $ARG 'bash -c "cd /srcML; git clean -fdx; git checkout develop; git pull"'

# copy large systems test cache so we don't have to pull back down the files every night
./sshall.py $ARG "bash -c \"cp -R /ci-build/cli/large_systems_test/cache/lst-cache"

# clear out old build directory, make new one, copy over large systems test cache
./sshall.py $ARG "bash -c \"rm -rf /ci-build; mkdir -p /ci-build/cli/large_systems_test/cache; mv /lst-cache /ci-build/cli/large_systems_test/cache\""

# configure cmake with every test enabled
./sshall.py $ARG "bash -c \"cd /ci-build; cmake -DBUILD_CLI_TESTS=ON -DBUILD_UNIT_TESTS=ON -DBUILD_TIMING_TESTS=ON -DBUILD_LARGE_SYSTEMS_TESTS=ON /srcML\""

# run ctest and post to cdash nightly using the given computer name specifying OS/version
./sshall.py $ARG "bash -c \"cd /ci-build; make -j2; ctest -VV -D Nightly -T MemCheck --overwrite Site='$NAME'\""
