#!/bin/bash

./prlctlall.py --test exec 'bash -c "cd srcML; svn update; cd ..; chown -R srcml:srcml srcML"'

URL="http://www.sdml.info/projects/srcml/trunk8"

curl ${URL}/srcML-Fedora15.tar.gz -o srcML.tar.gz
scp srcML.tar.gz fedora15test:/srcML
curl ${URL}/srcML-Fedora16.tar.gz -o srcML.tar.gz
scp srcML.tar.gz fedora16test:/srcML
curl ${URL}/srcML-Fedora17.tar.gz -o srcML.tar.gz
scp srcML.tar.gz fedora17test:/srcML

curl ${URL}/srcML-Fedora15-64.tar.gz -o srcML.tar.gz
scp srcML.tar.gz fedora15test64:/srcML
curl ${URL}/srcML-Fedora16-64.tar.gz -o srcML.tar.gz
scp srcML.tar.gz fedora16test64:/srcML
curl ${URL}/srcML-Fedora17-64.tar.gz -o srcML.tar.gz
scp srcML.tar.gz fedora17test64:/srcML

curl ${URL}/srcML-Ubuntu10.04.tar.gz -o srcML.tar.gz
scp srcML.tar.gz ubuntu10test:/srcML
curl ${URL}/srcML-Ubuntu11.04.tar.gz -o srcML.tar.gz
scp srcML.tar.gz ubuntu11test:/srcML
curl ${URL}/srcML-Ubuntu12.04.tar.gz -o srcML.tar.gz
scp srcML.tar.gz ubuntu12test:/srcML

curl ${URL}/srcML-Ubuntu10.04-64.tar.gz -o srcML.tar.gz
scp srcML.tar.gz ubuntu10test64:/srcML
curl ${URL}/srcML-Ubuntu11.04-64.tar.gz -o srcML.tar.gz
scp srcML.tar.gz ubuntu11test64:/srcML
curl ${URL}/srcML-Ubuntu12.04-64.tar.gz -o srcML.tar.gz
scp srcML.tar.gz ubuntu12test64:/srcML

curl ${URL}/srcML-OSX.tar.gz -o srcML.tar.gz
cp srcML.tar.gz ~/srcML

./prlctlall.py --test exec 'bash -c "cd srcML; tar xvf srcML.tar.gz"'
./prlctlall.py --test exec 'bash -c "export SRC2SRCML=\"/srcML/srcML/src2srcml\"; export SRCML2SRC=\"/srcML/srcML/srcml2src\"; cd srcML/trunk/test/; rm -f srcMLTestReport*; make clean; make;"'

cd srcML
svn update
tar xvf srcML.tar.gz
export SRC2SRCML="../../srcML/src2srcml"
export SRCML2SRC="../../srcML/srcml2src"
cd trunk/test/
rm -f srcMLTestReport*
make clean; make

~/prlctlall.py --test exec 'bash -c "grep -a \"Errors:\" srcML/trunk/test/srcMLTestReport*"'
grep -a "Errors:" srcMLTestReport*