#!/bin/bash

./vmctl.py --fedora --test resume
./test_srcML fedora
./vmctl.py --fedora --test suspend

./vmctl.py --ubuntu --test resume
./test_srcML ubuntu
./vmctl.py --ubuntu --test suspend

./vmctl.py --mint --test resume
./test_srcML mint
./vmctl.py --mint --test suspend

./vmctl.py --suse --test resume
./test_srcML suse
./vmctl.py --suse --test suspend

./vmctl.py --mac --test resume
./test_srcML mac
./vmctl.py --mac --test suspend