#!/bin/bash

./vmctl.py --fedora --build resume; sleep 15
./sshall.py --fedora --build 'bash -c "yes | yum update; yes | yum upgrade"'
./vmctl.py --fedora --build suspend

./vmctl.py --fedora --test resume; sleep 15
./sshall.py --fedora --test 'bash -c "yes | yum update; yes | yum upgrade"'
./vmctl.py --fedora --test suspend

./vmctl.py --ubuntu --build resume; sleep 15
./sshall.py --ubuntu --build 'bash -c "yes | apt-get update; yes | apt-get upgrade"'
./vmctl.py --ubuntu --build suspend

./vmctl.py --ubuntu --test resume; sleep 15
./sshall.py --ubuntu --test 'bash -c "yes | apt-get update; yes | apt-get upgrade"'
./vmctl.py --ubuntu --test suspend

./vmctl.py --mint --build --13 resume; sleep 15
./sshall.py --mint --build --13 'bash -c "yes | apt-get update; yes | apt-get upgrade"'
./vmctl.py --mint --build --13 suspend

./vmctl.py --mint --build --~13 resume; sleep 15
./sshall.py --mint --build --~13 'bash -c "yes | apt-get update; yes | apt-get upgrade"'
./vmctl.py --mint --build --~13 suspend

./vmctl.py --mint --test --13 resume; sleep 15
./sshall.py --mint --test --13 'bash -c "yes | apt-get update; yes | apt-get upgrade"'
./vmctl.py --mint --test --13 suspend

./vmctl.py --mint --test --~13 resume; sleep 15
./sshall.py --mint --test --~13 'bash -c "yes | apt-get update; yes | apt-get upgrade"'
./vmctl.py --mint --test --~13 suspend

./vmctl.py --suse --build resume; sleep 15
./sshall.py --suse --build 'bash -c "zypper --non-interactive update --auto-agree-with-licenses"'
./vmctl.py --suse --build suspend

./vmctl.py --suse --test resume; sleep 15
./sshall.py --suse --test 'bash -c "zypper --non-interactive update --auto-agree-with-licenses"'
./vmctl.py --suse --test suspend

./vmctl.py --~mac snapshot "--name \"Update: $(date '+%B %e, %Y')\""
