#!/bin/bash

./prlctlall.py --test exec 'bash -c "cd srcML; svn update; cd ..; chown -R srcml:srcml srcML"'

scp ~/Dropbox/srcML/Unix/Fedora15/srcML.tar.gz fedora15test:/srcML
scp ~/Dropbox/srcML/Unix/Fedora16/srcML.tar.gz fedora16test:/srcML
scp ~/Dropbox/srcML/Unix/Fedora17/srcML.tar.gz fedora17test:/srcML

scp ~/Dropbox/srcML/Unix/Fedora15-64/srcML.tar.gz fedora15test64:/srcML
scp ~/Dropbox/srcML/Unix/Fedora16-64/srcML.tar.gz fedora16test64:/srcML
scp ~/Dropbox/srcML/Unix/Fedora17-64/srcML.tar.gz fedora17test64:/srcML

scp ~/Dropbox/srcML/Unix/Ubuntu10.04/srcML.tar.gz ubuntu10test:/srcML
scp ~/Dropbox/srcML/Unix/Ubuntu11.04/srcML.tar.gz ubuntu11test:/srcML
scp ~/Dropbox/srcML/Unix/Ubuntu12.04/srcML.tar.gz ubuntu12test:/srcML

scp ~/Dropbox/srcML/Unix/Ubuntu10.04-64/srcML.tar.gz ubuntu10test64:/srcML
scp ~/Dropbox/srcML/Unix/Ubuntu11.04-64/srcML.tar.gz ubuntu11test64:/srcML
scp ~/Dropbox/srcML/Unix/Ubuntu12.04-64/srcML.tar.gz ubuntu12test64:/srcML

cp ~/Dropbox/srcML/Unix/OSX/srcML.tar.gz ~/srcML

./prlctlall.py --test exec 'bash -c "cd srcML; tar xvf srcML.tar.gz"'
./prlctlall.py --test exec 'bash -c "export SRC2SRCML=\"/srcML/srcML/src2srcml\"; export SRCML2SRC=\"/srcML/srcML/srcml2src\"; cd srcML/trunk/test/cli; make clean; make;"'

cd srcML
svn update
tar xvf srcML.tar.gz
export SRC2SRCML="../../srcML/src2srcml"
export SRCML2SRC="../../srcML/srcml2src"
cd trunk/test/cli
make clean; make
