#!/bin/bash

src2srcml empty.cpp | diff - empty.default.cpp.xml
cat empty.cpp | src2srcml | diff - empty.default.cpp.xml
cat empty.cpp | src2srcml - | diff - empty.default.cpp.xml

src2srcml empty.cpp out.xml; diff out.xml empty.default.cpp.xml

cat empty.cpp | src2srcml - out.xml; diff out.xml empty.default.cpp.xml

# xml encoding specification (UTF-8) is standard
src2srcml -x ISO-8859-1 empty.cpp | diff - empty.iso-8859-1.cpp.xml
