#!/bin/bash

function perform() { echo $1; }

echo src2srcml empty.cpp
src2srcml empty.cpp | diff - empty.default.cpp.xml

echo src2srcml
cat empty.cpp | src2srcml | diff - empty.noname.default.cpp.xml

echo src2srcml -
cat empty.cpp | src2srcml - | diff - empty.noname.default.cpp.xml

command="src2srcml empty.cpp out.xml"
echo $command
$command; diff out.xml empty.default.cpp.xml

echo src2srcml - out.xml
cat empty.cpp | src2srcml - out.xml; diff out.xml empty.noname.default.cpp.xml

echo -e "\n# src2srcml help\n"

# help
echo src2srcml --help
src2srcml --help | diff - src2srcml.help.txt

echo src2srcml -h
src2srcml -h | diff - src2srcml.help.txt

echo src2srcml -hg
src2srcml -hg | diff - src2srcml.help.txt

echo src2srcml -gh
src2srcml -gh | diff - src2srcml.help.txt

echo src2srcml -Vh
src2srcml -Vh | diff - src2srcml.help.txt

echo -e "\n# src2srcml xml encoding specification (UTF-8) is standard\n"

for encoding in "ISO-8859-1" "UTF-8"
do

for form in "-x " "--xml-encoding " "--xml-encoding="
do
command="src2srcml $form$encoding empty.cpp"
echo $command
$command | diff - empty.$encoding.cpp.xml

rm -f result.xml

command="src2srcml $form$encoding empty.cpp result.xml"
echo $command
$command; diff result.xml empty.$encoding.cpp.xml

done

echo src2srcml --xml-encoding "$encoding" empty.cpp
src2srcml --xml-encoding "$encoding" empty.cpp | diff - empty.$encoding.cpp.xml

rm -f result.xml
echo src2srcml --xml-encoding "$encoding" empty.cpp result.xml
src2srcml --xml-encoding "$encoding" empty.cpp result.xml; diff result.xml empty.$encoding.cpp.xml
done

echo -e "\n# src2srcml language\n"

for lang in "C" "C++" "Java"
do

for form in "-l " "--language " "--language="
do
echo src2srcml $form$lang empty.cpp
src2srcml $form$lang empty.cpp | diff - empty.$lang.cpp.xml

rm -f result.xml
echo src2srcml $form$lang empty.cpp result.xml
src2srcml $form$lang empty.cpp result.xml;  diff result.xml empty.$lang.cpp.xml
done

echo src2srcml --language "$lang" empty.cpp
src2srcml --language "$lang" empty.cpp | diff - empty.$lang.cpp.xml

rm -f result.xml
echo src2srcml --language "$lang" empty.cpp result.xml
src2srcml --language "$lang" empty.cpp result.xml;  diff result.xml empty.$lang.cpp.xml
done

# srcml2src language
for lang in "C" "C++" "Java"
do

rm -f result
echo "$lang" > result
for form in "-l" "--language"
do
echo srcml2src $form empty.$lang.cpp.xml
srcml2src $form empty.$lang.cpp.xml | diff - result
done

done

echo -e "\n# src2srcml filename\n"

for name in "main.cpp"
do

for form in "-f " "--filename " "--filename="
do
command="src2srcml $form$name empty.cpp"
echo $command
$command | diff - empty.main_cpp.cpp.xml
rm -f result.xml
command="src2srcml $form$name empty.cpp result.xml"
perform "$command" "diff result.xml empty.main_cpp.cpp.xml"
$command;  diff result.xml empty.main_cpp.cpp.xml
done

echo src2srcml --filename "$name" empty.cpp
src2srcml --filename "$name" empty.cpp | diff empty.main_cpp.cpp.xml -

rm -f result.xml
echo src2srcml --filename "$name" empty.cpp result.xml
src2srcml --filename "$name" empty.cpp result.xml;  diff empty.main_cpp.cpp.xml result.xml

done

echo -e "\n# src2srcml directory\n"

for name in "foo"
do

for form in "-d " "--directory " "--directory="
do
command="src2srcml $form$name main.cpp"
echo $command
$command | diff - empty.dirfoo.main_cpp.cpp.xml
rm -f result.xml
command="src2srcml $form$name main.cpp result.xml"
perform "$command" "diff result.xml empty.main_cpp.cpp.xml"
$command;  diff result.xml empty.dirfoo.main_cpp.cpp.xml
done

echo src2srcml --directory "$name" main.cpp
src2srcml --directory "$name" main.cpp | diff empty.dirfoo.main_cpp.cpp.xml -

rm -f result.xml
echo src2srcml --directory "$name" main.cpp result.xml
src2srcml --directory "$name" main.cpp result.xml;  diff empty.dirfoo.main_cpp.cpp.xml result.xml

done

echo -e "\n# src2srcml directory and filename\n"

for dname in "foo"
do

for fname in "main.cpp"
do

for fform in  "-f " "--filename " "--filename="
do

for dform in "-d " "--directory " "--directory="
do
command="src2srcml $dform$dname $fform$fname main.cpp"
echo $command
$command | diff - empty.dirfoo.main_cpp.cpp.xml
rm -f result.xml
command="src2srcml $dform$dname $fform$fname empty.cpp result.xml"
perform "$command" "diff result.xml empty.main_cpp.cpp.xml"
$command;  diff result.xml empty.dirfoo.main_cpp.cpp.xml
done

echo src2srcml --directory "$dname" --filename "$fname" empty.cpp
src2srcml --directory "$dname" --filename "$fname" empty.cpp | diff empty.dirfoo.main_cpp.cpp.xml -

rm -f result.xml
echo src2srcml --directory "$dname" --filename "$fname" empty.cpp result.xml
src2srcml --directory "$dname" --filename "$fname" empty.cpp result.xml;  diff empty.dirfoo.main_cpp.cpp.xml result.xml

done

done

done
