To build the srcML Toolkit (src2srcml, srcml2src, srcml and libsrcml)
run the following in the src directory to generate a makefile in unix:

cmake .

This can be run from the top-level or srce directory.
After completion, make will build the project.


