SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/Users/mdecker/Documents/Projects/srcML/trunk/src;srcML;ALL;/")
set(CPACK_PACKAGE_DESCRIPTION "srcML Toolkit")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "srcML built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "srcML")
SET(CPACK_PACKAGE_NAME "srcML")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VERSION "0.1.1")
SET(CPACK_STRIP_FILES "bin")

SET(CPACK_IGNORE_FILES "\\.svn/;\\.git;.*~;\\..*")
set(CPACK_SOURCE_PACKAGE_FILE_NAME srcML-src)

