---
name: Build Windows

on: workflow_dispatch

permissions:
  packages: write

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    environment: build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: ./.github/actions/vcpkg
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: ci-msvc

      - name: List packages
        working-directory: build
        continue-on-error: true
        run: |
          cpack -V
          dir dist/*

      - name: Upload all CPack config files
        uses: actions/upload-artifact@v4
        with:
          name: cpack-configs
          path: |
            build/**/CPackConfig.cmake
            build/**/CPackSourceConfig.cmake

      - uses: actions/upload-artifact@v4
        with:
          name: "Windows Packages"
          path: |
            build/dist/*.msi
            build/dist/*.zip
            build/dist/*.exe
            build/dist/*.nupkg
